name: Test & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install and build DI
        run: |
          go install github.com/google/wire/cmd/wire@latest
          wire ./cmd/...

      - name: Generate mocks
        run: |
          go install github.com/vektra/mockery/v2@latest
          mockery --dir=domain/interactor --name=MemInteractor
          mockery --dir=domain/interactor --name=RecordInteractor
          mockery --dir=domain/repository --name=MemRepository
          mockery --dir=domain/repository --name=RecordRepository
          mockery --dir=domain/validator --name=MemValidator
          mockery --dir=domain/validator --name=RecordValidator

      - name: Test
        run: go test -v ./...

      - name: Dispatch docker image build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: SananGuliyev/gossignment
          event-type: docker-image
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
